### ISSUE TITLE
/market restrict fails if the reason is left blank

### ISSUE THREAD

**Issue by NeedlessMemeing** [PixliesEarth/PixliesCoreV2#24]
https://github.com/PixliesEarth/PixliesCoreV2/blob/6d0ef0cff5709c064101d3ec0caff0a1dc2fce7a/ProtoBusiness/src/main/java/net/pixlies/business/commands/impl/MarketCommand.java#L113
@vyketype 

Most likely just an issue of the command assuming that a reason was entered.
![image](https://user-images.githubusercontent.com/37240761/181696907-d044b156-598e-4551-b8b0-8a3bb64268d8.png)
![image](https://user-images.githubusercontent.com/37240761/181696977-ca4b1856-8dae-44b4-9d3d-5dd09cb2a408.png)

**Comment by vyketype** [comment]
Should be fixed with the latest commit.
