### ISSUE TITLE
/market GUI bug

### ISSUE THREAD

**Issue by NeedlessMemeing** [PixliesEarth/PixliesCoreV2#27]
https://github.com/PixliesEarth/PixliesCoreV2/blob/6d0ef0cff5709c064101d3ec0caff0a1dc2fce7a/ProtoBusiness/src/main/java/net/pixlies/business/market/orders/OrderProfile.java#L162

@vyketype 

Something odd is happening whenever /market is used.

![image](https://user-images.githubusercontent.com/37240761/181703323-6cabac65-98ef-4482-b515-ad99934cb7af.png)

**Comment by vyketype** [comment]
Yes, this will be fixed soon because I will use another library.
