### ISSUE TITLE
Finished German Translation for PixliesProxyCore

### ISSUE THREAD

**Issue by TAMaurice** [PixliesEarth/PixliesCoreV2#34]
Title says it all
[LANG_GER.txt](https://github.com/PixliesEarth/PixliesCoreV2/files/10311280/LANG_GER.txt)
Add it to PixliesCoreV2/PixliesProxyCore/resources/language
or whatever it was please.

**Comment by vyketype** [comment]
Ok, make a pull request, and I'll approve it.
